// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien.Api.Data;

#nullable disable

namespace QuanLySinhVien.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921104243_LinkAcademicProfilesToUsers")]
    partial class LinkAcademicProfilesToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.BuoiHoc", b =>
                {
                    b.Property<string>("MaBuoiHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLichHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayHocCuThe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDiemDanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiBuoiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBuoiHoc");

                    b.HasIndex("MaLichHoc");

                    b.ToTable("BuoiHoc", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.ChiTietDiemDanh", b =>
                {
                    b.Property<string>("MaBuoiHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ThoiGianCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBuoiHoc", "MaSinhVien");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("ChiTietDiemDanh", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.DanhSachSinhVienLop", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaLopHocPhan")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongSoBuoiVang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiCanhBao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSinhVien", "MaLopHocPhan");

                    b.HasIndex("MaLopHocPhan");

                    b.ToTable("DanhSachSinhVienLop", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiTaiKhoan")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.HoSoKhuonMat", b =>
                {
                    b.Property<string>("MaHoSo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("VectorJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaSinhVien")
                        .IsUnique();

                    b.ToTable("HoSoKhuonMat", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.HocKyThucTe", b =>
                {
                    b.Property<string>("MaHocKy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LoaiHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHocKy");

                    b.ToTable("HocKyThucTe", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.LichHoc", b =>
                {
                    b.Property<string>("MaLichHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLopHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaLopHocPhan");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichHoc", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.LopHocPhan", b =>
                {
                    b.Property<string>("MaLopHocPhan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLopHocPhan");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.MonHoc", b =>
                {
                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoTinChiLyThuyet")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChiThucHanh")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaMonHoc");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.PhienDiemDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DongLucUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HetHanLucUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaBuoiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MoLucUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrTokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaBuoiHoc");

                    b.HasIndex("QrTokenHash")
                        .IsUnique();

                    b.ToTable("PhienDiemDanh", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.PhongHoc", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DiaChiCoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongHoc", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị hệ thống",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cán bộ quản lý",
                            Name = "CanBoQuanLy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Giảng viên",
                            Name = "GiangVien"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sinh viên",
                            Name = "SinhVien"
                        });
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiTaiKhoan")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.ThongBao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HieuLucTuUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaLopHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TaoLucUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.BuoiHoc", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.LichHoc", "LichHoc")
                        .WithMany("BuoiHocs")
                        .HasForeignKey("MaLichHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.ChiTietDiemDanh", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.BuoiHoc", "BuoiHoc")
                        .WithMany("ChiTietDiemDanhs")
                        .HasForeignKey("MaBuoiHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySinhVien.Api.Models.Entities.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuoiHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.DanhSachSinhVienLop", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySinhVien.Api.Models.Entities.SinhVien", "SinhVien")
                        .WithMany("DangKyLop")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.GiangVien", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("QuanLySinhVien.Api.Models.Entities.GiangVien", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.HoSoKhuonMat", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.SinhVien", "SinhVien")
                        .WithOne("HoSoKhuonMat")
                        .HasForeignKey("QuanLySinhVien.Api.Models.Entities.HoSoKhuonMat", "MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.LichHoc", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySinhVien.Api.Models.Entities.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.LopHocPhan", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLySinhVien.Api.Models.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.PhienDiemDanh", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.BuoiHoc", "BuoiHoc")
                        .WithMany()
                        .HasForeignKey("MaBuoiHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuoiHoc");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.SinhVien", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("QuanLySinhVien.Api.Models.Entities.SinhVien", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.UserRole", b =>
                {
                    b.HasOne("QuanLySinhVien.Api.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySinhVien.Api.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.BuoiHoc", b =>
                {
                    b.Navigation("ChiTietDiemDanhs");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.LichHoc", b =>
                {
                    b.Navigation("BuoiHocs");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.LopHocPhan", b =>
                {
                    b.Navigation("DanhSachSinhVien");

                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.SinhVien", b =>
                {
                    b.Navigation("DangKyLop");

                    b.Navigation("HoSoKhuonMat");
                });

            modelBuilder.Entity("QuanLySinhVien.Api.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
